project: CJHJ/convolutional-neural-markov-model
name: data-generation-diffusion

hydra:
    run:
        dir: ./data/diffusion/

parameters:
    data_path: ./normal/train/
    n_simulations: 25
    simulation_length: 2001
    n_samples: 30
    sample_length: 50
    sample_time_difference: 3
    temp_base: 0
    temp_low: 500
    temp_high: 700
    radius_min: 0.5
    radius_max: 5
    center_x_min: 0
    center_x_max: 10
    center_y_min: 0
    center_y_max: 10
    transition_loc: 0
    transition_scale: 3
    transition_noise_type: cauchy
    emission_loc: 0
    emission_scale: 10
    emission_noise_type: cauchy